#!/bin/bash

if [ -z $1 ]; then
	prefix=/usr/local
else
	prefix=$1
fi

if [ ! -d $prefix ]; then
	echo "Specified directory ($prefix) doesn't exist"
	exit 1
fi

rm -rf $prefix/bin/mpiCC
rm -rf $prefix/bin/mpiCC-vt
rm -rf $prefix/bin/mpic++
rm -rf $prefix/bin/mpic++-vt
rm -rf $prefix/bin/mpicc
rm -rf $prefix/bin/mpicc-vt
rm -rf $prefix/bin/mpicxx
rm -rf $prefix/bin/mpicxx-vt
rm -rf $prefix/bin/mpiexec
rm -rf $prefix/bin/mpif77
rm -rf $prefix/bin/mpif77-vt
rm -rf $prefix/bin/mpif90
rm -rf $prefix/bin/mpif90-vt
rm -rf $prefix/bin/mpifort
rm -rf $prefix/bin/mpifort-vt
rm -rf $prefix/bin/mpirun
rm -rf $prefix/bin/mpivars.csh
rm -rf $prefix/bin/mpivars.sh
rm -rf $prefix/bin/ompi-clean
rm -rf $prefix/bin/ompi-ps
rm -rf $prefix/bin/ompi-server
rm -rf $prefix/bin/ompi-top
rm -rf $prefix/bin/ompi_info
rm -rf $prefix/bin/opal_wrapper
rm -rf $prefix/bin/opalc++
rm -rf $prefix/bin/opalcc
rm -rf $prefix/bin/opari
rm -rf $prefix/bin/orte-clean
rm -rf $prefix/bin/orte-info
rm -rf $prefix/bin/orte-ps
rm -rf $prefix/bin/orte-server
rm -rf $prefix/bin/orte-top
rm -rf $prefix/bin/ortecc
rm -rf $prefix/bin/orted
rm -rf $prefix/bin/orterun
rm -rf $prefix/bin/oshcc
rm -rf $prefix/bin/oshfort
rm -rf $prefix/bin/oshmem_info
rm -rf $prefix/bin/oshrun
rm -rf $prefix/bin/otfaux
rm -rf $prefix/bin/otfcompress
rm -rf $prefix/bin/otfconfig
rm -rf $prefix/bin/otfdecompress
rm -rf $prefix/bin/otfinfo
rm -rf $prefix/bin/otfmerge
rm -rf $prefix/bin/otfmerge-mpi
rm -rf $prefix/bin/otfprint
rm -rf $prefix/bin/otfprofile
rm -rf $prefix/bin/otfprofile-mpi
rm -rf $prefix/bin/otfshrink
rm -rf $prefix/bin/shmemcc
rm -rf $prefix/bin/shmemfort
rm -rf $prefix/bin/shmemrun
rm -rf $prefix/bin/vtCC
rm -rf $prefix/bin/vtc++
rm -rf $prefix/bin/vtcc
rm -rf $prefix/bin/vtcxx
rm -rf $prefix/bin/vtf77
rm -rf $prefix/bin/vtf90
rm -rf $prefix/bin/vtfilter
rm -rf $prefix/bin/vtfilter-mpi
rm -rf $prefix/bin/vtfiltergen
rm -rf $prefix/bin/vtfiltergen-mpi
rm -rf $prefix/bin/vtfort
rm -rf $prefix/bin/vtrun
rm -rf $prefix/bin/vtsetup
rm -rf $prefix/bin/vtsetup.jar
rm -rf $prefix/bin/vtunify
rm -rf $prefix/bin/vtunify-mpi
rm -rf $prefix/bin/vtwrapper
rm -rf $prefix/etc/openmpi-default-hostfile
rm -rf $prefix/etc/openmpi-mca-params.conf
rm -rf $prefix/etc/openmpi-totalview.tcl
rm -rf $prefix/etc/vtsetup-config.dtd
rm -rf $prefix/etc/vtsetup-config.xml
rm -rf $prefix/include/mpi-ext.h
rm -rf $prefix/include/mpi.h
rm -rf $prefix/include/mpi_portable_platform.h
rm -rf $prefix/include/mpif-config.h
rm -rf $prefix/include/mpif-constants.h
rm -rf $prefix/include/mpif-ext.h
rm -rf $prefix/include/mpif-externals.h
rm -rf $prefix/include/mpif-handles.h
rm -rf $prefix/include/mpif-io-constants.h
rm -rf $prefix/include/mpif-io-handles.h
rm -rf $prefix/include/mpif-sentinels.h
rm -rf $prefix/include/mpif-sizeof.h
rm -rf $prefix/include/mpif.h
rm -rf $prefix/include/mpp
rm -rf $prefix/include/openmpi
rm -rf $prefix/include/pshmem.h
rm -rf $prefix/include/pshmemx.h
rm -rf $prefix/include/shmem-compat.h
rm -rf $prefix/include/shmem.fh
rm -rf $prefix/include/shmem.h
rm -rf $prefix/include/shmemx.h
rm -rf $prefix/include/vampirtrace
rm -rf $prefix/lib64/libmca_common_sm.la
rm -rf $prefix/lib64/libmca_common_sm.so
rm -rf $prefix/lib64/libmca_common_sm.so.4
rm -rf $prefix/lib64/libmca_common_sm.so.4.0.4
rm -rf $prefix/lib64/libmca_common_verbs.la
rm -rf $prefix/lib64/libmca_common_verbs.so
rm -rf $prefix/lib64/libmca_common_verbs.so.0
rm -rf $prefix/lib64/libmca_common_verbs.so.0.2.3
rm -rf $prefix/lib64/libmpi.la
rm -rf $prefix/lib64/libmpi.so
rm -rf $prefix/lib64/libmpi.so.1
rm -rf $prefix/lib64/libmpi.so.1.6.0
rm -rf $prefix/lib64/libmpi_cxx.la
rm -rf $prefix/lib64/libmpi_cxx.so
rm -rf $prefix/lib64/libmpi_cxx.so.1
rm -rf $prefix/lib64/libmpi_cxx.so.1.1.3
rm -rf $prefix/lib64/libmpi_mpifh.la
rm -rf $prefix/lib64/libmpi_mpifh.so
rm -rf $prefix/lib64/libmpi_mpifh.so.2
rm -rf $prefix/lib64/libmpi_mpifh.so.2.5.0
rm -rf $prefix/lib64/libmpi_usempi.la
rm -rf $prefix/lib64/libmpi_usempi.so
rm -rf $prefix/lib64/libmpi_usempi.so.1
rm -rf $prefix/lib64/libmpi_usempi.so.1.4.0
rm -rf $prefix/lib64/libompitrace.la
rm -rf $prefix/lib64/libompitrace.so
rm -rf $prefix/lib64/libompitrace.so.0
rm -rf $prefix/lib64/libompitrace.so.0.0.0
rm -rf $prefix/lib64/libopen-pal.la
rm -rf $prefix/lib64/libopen-pal.so
rm -rf $prefix/lib64/libopen-pal.so.6
rm -rf $prefix/lib64/libopen-pal.so.6.2.1
rm -rf $prefix/lib64/libopen-rte.la
rm -rf $prefix/lib64/libopen-rte.so
rm -rf $prefix/lib64/libopen-rte.so.7
rm -rf $prefix/lib64/libopen-rte.so.7.0.5
rm -rf $prefix/lib64/libopen-trace-format.a
rm -rf $prefix/lib64/libopen-trace-format.la
rm -rf $prefix/lib64/libopen-trace-format.so
rm -rf $prefix/lib64/libopen-trace-format.so.1
rm -rf $prefix/lib64/libopen-trace-format.so.1.0.0
rm -rf $prefix/lib64/liboshmem.la
rm -rf $prefix/lib64/liboshmem.so
rm -rf $prefix/lib64/liboshmem.so.3
rm -rf $prefix/lib64/liboshmem.so.3.0.1
rm -rf $prefix/lib64/libotfaux.a
rm -rf $prefix/lib64/libotfaux.la
rm -rf $prefix/lib64/libotfaux.so
rm -rf $prefix/lib64/libotfaux.so.0
rm -rf $prefix/lib64/libotfaux.so.0.0.0
rm -rf $prefix/lib64/libvt-hyb.a
rm -rf $prefix/lib64/libvt-hyb.la
rm -rf $prefix/lib64/libvt-hyb.so
rm -rf $prefix/lib64/libvt-hyb.so.0
rm -rf $prefix/lib64/libvt-hyb.so.0.0.0
rm -rf $prefix/lib64/libvt-mpi-unify.a
rm -rf $prefix/lib64/libvt-mpi-unify.la
rm -rf $prefix/lib64/libvt-mpi-unify.so
rm -rf $prefix/lib64/libvt-mpi-unify.so.0
rm -rf $prefix/lib64/libvt-mpi-unify.so.0.0.0
rm -rf $prefix/lib64/libvt-mpi.a
rm -rf $prefix/lib64/libvt-mpi.la
rm -rf $prefix/lib64/libvt-mpi.so
rm -rf $prefix/lib64/libvt-mpi.so.0
rm -rf $prefix/lib64/libvt-mpi.so.0.0.0
rm -rf $prefix/lib64/libvt-mt.a
rm -rf $prefix/lib64/libvt-mt.la
rm -rf $prefix/lib64/libvt-mt.so
rm -rf $prefix/lib64/libvt-mt.so.0
rm -rf $prefix/lib64/libvt-mt.so.0.0.0
rm -rf $prefix/lib64/libvt-pomp.a
rm -rf $prefix/lib64/libvt-pomp.la
rm -rf $prefix/lib64/libvt.a
rm -rf $prefix/lib64/libvt.la
rm -rf $prefix/lib64/libvt.so
rm -rf $prefix/lib64/libvt.so.0
rm -rf $prefix/lib64/libvt.so.0.0.0
rm -rf $prefix/lib64/mpi.mod
rm -rf $prefix/lib64/openmpi
rm -rf $prefix/lib64/pkgconfig/ompi-c.pc
rm -rf $prefix/lib64/pkgconfig/ompi-cxx.pc
rm -rf $prefix/lib64/pkgconfig/ompi-f77.pc
rm -rf $prefix/lib64/pkgconfig/ompi-f90.pc
rm -rf $prefix/lib64/pkgconfig/ompi-fort.pc
rm -rf $prefix/lib64/pkgconfig/ompi.pc
rm -rf $prefix/lib64/pkgconfig/opal.pc
rm -rf $prefix/lib64/pkgconfig/orte.pc
rm -rf $prefix/openmpi
rm -rf $prefix/share/man/man1/mpiCC.1
rm -rf $prefix/share/man/man1/mpic++.1
rm -rf $prefix/share/man/man1/mpicc.1
rm -rf $prefix/share/man/man1/mpicxx.1
rm -rf $prefix/share/man/man1/mpiexec.1
rm -rf $prefix/share/man/man1/mpif77.1
rm -rf $prefix/share/man/man1/mpif90.1
rm -rf $prefix/share/man/man1/mpifort.1
rm -rf $prefix/share/man/man1/mpirun.1
rm -rf $prefix/share/man/man1/ompi-clean.1
rm -rf $prefix/share/man/man1/ompi-ps.1
rm -rf $prefix/share/man/man1/ompi-server.1
rm -rf $prefix/share/man/man1/ompi-top.1
rm -rf $prefix/share/man/man1/ompi_info.1
rm -rf $prefix/share/man/man1/opal_wrapper.1
rm -rf $prefix/share/man/man1/opalc++.1
rm -rf $prefix/share/man/man1/opalcc.1
rm -rf $prefix/share/man/man1/orte-clean.1
rm -rf $prefix/share/man/man1/orte-info.1
rm -rf $prefix/share/man/man1/orte-ps.1
rm -rf $prefix/share/man/man1/orte-server.1
rm -rf $prefix/share/man/man1/orte-top.1
rm -rf $prefix/share/man/man1/orted.1
rm -rf $prefix/share/man/man1/orterun.1
rm -rf $prefix/share/man/man1/oshmem_info.1
rm -rf $prefix/share/man/man3/MPI.3
rm -rf $prefix/share/man/man3/MPI_Abort.3
rm -rf $prefix/share/man/man3/MPI_Accumulate.3
rm -rf $prefix/share/man/man3/MPI_Add_error_class.3
rm -rf $prefix/share/man/man3/MPI_Add_error_code.3
rm -rf $prefix/share/man/man3/MPI_Add_error_string.3
rm -rf $prefix/share/man/man3/MPI_Address.3
rm -rf $prefix/share/man/man3/MPI_Allgather.3
rm -rf $prefix/share/man/man3/MPI_Allgatherv.3
rm -rf $prefix/share/man/man3/MPI_Alloc_mem.3
rm -rf $prefix/share/man/man3/MPI_Allreduce.3
rm -rf $prefix/share/man/man3/MPI_Alltoall.3
rm -rf $prefix/share/man/man3/MPI_Alltoallv.3
rm -rf $prefix/share/man/man3/MPI_Alltoallw.3
rm -rf $prefix/share/man/man3/MPI_Attr_delete.3
rm -rf $prefix/share/man/man3/MPI_Attr_get.3
rm -rf $prefix/share/man/man3/MPI_Attr_put.3
rm -rf $prefix/share/man/man3/MPI_Barrier.3
rm -rf $prefix/share/man/man3/MPI_Bcast.3
rm -rf $prefix/share/man/man3/MPI_Bsend.3
rm -rf $prefix/share/man/man3/MPI_Bsend_init.3
rm -rf $prefix/share/man/man3/MPI_Buffer_attach.3
rm -rf $prefix/share/man/man3/MPI_Buffer_detach.3
rm -rf $prefix/share/man/man3/MPI_Cancel.3
rm -rf $prefix/share/man/man3/MPI_Cart_coords.3
rm -rf $prefix/share/man/man3/MPI_Cart_create.3
rm -rf $prefix/share/man/man3/MPI_Cart_get.3
rm -rf $prefix/share/man/man3/MPI_Cart_map.3
rm -rf $prefix/share/man/man3/MPI_Cart_rank.3
rm -rf $prefix/share/man/man3/MPI_Cart_shift.3
rm -rf $prefix/share/man/man3/MPI_Cart_sub.3
rm -rf $prefix/share/man/man3/MPI_Cartdim_get.3
rm -rf $prefix/share/man/man3/MPI_Close_port.3
rm -rf $prefix/share/man/man3/MPI_Comm_accept.3
rm -rf $prefix/share/man/man3/MPI_Comm_c2f.3
rm -rf $prefix/share/man/man3/MPI_Comm_call_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Comm_compare.3
rm -rf $prefix/share/man/man3/MPI_Comm_connect.3
rm -rf $prefix/share/man/man3/MPI_Comm_create.3
rm -rf $prefix/share/man/man3/MPI_Comm_create_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Comm_create_group.3
rm -rf $prefix/share/man/man3/MPI_Comm_create_keyval.3
rm -rf $prefix/share/man/man3/MPI_Comm_delete_attr.3
rm -rf $prefix/share/man/man3/MPI_Comm_disconnect.3
rm -rf $prefix/share/man/man3/MPI_Comm_dup.3
rm -rf $prefix/share/man/man3/MPI_Comm_dup_with_info.3
rm -rf $prefix/share/man/man3/MPI_Comm_f2c.3
rm -rf $prefix/share/man/man3/MPI_Comm_free.3
rm -rf $prefix/share/man/man3/MPI_Comm_free_keyval.3
rm -rf $prefix/share/man/man3/MPI_Comm_get_attr.3
rm -rf $prefix/share/man/man3/MPI_Comm_get_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Comm_get_info.3
rm -rf $prefix/share/man/man3/MPI_Comm_get_name.3
rm -rf $prefix/share/man/man3/MPI_Comm_get_parent.3
rm -rf $prefix/share/man/man3/MPI_Comm_group.3
rm -rf $prefix/share/man/man3/MPI_Comm_idup.3
rm -rf $prefix/share/man/man3/MPI_Comm_join.3
rm -rf $prefix/share/man/man3/MPI_Comm_rank.3
rm -rf $prefix/share/man/man3/MPI_Comm_remote_group.3
rm -rf $prefix/share/man/man3/MPI_Comm_remote_size.3
rm -rf $prefix/share/man/man3/MPI_Comm_set_attr.3
rm -rf $prefix/share/man/man3/MPI_Comm_set_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Comm_set_info.3
rm -rf $prefix/share/man/man3/MPI_Comm_set_name.3
rm -rf $prefix/share/man/man3/MPI_Comm_size.3
rm -rf $prefix/share/man/man3/MPI_Comm_spawn.3
rm -rf $prefix/share/man/man3/MPI_Comm_spawn_multiple.3
rm -rf $prefix/share/man/man3/MPI_Comm_split.3
rm -rf $prefix/share/man/man3/MPI_Comm_split_type.3
rm -rf $prefix/share/man/man3/MPI_Comm_test_inter.3
rm -rf $prefix/share/man/man3/MPI_Compare_and_swap.3
rm -rf $prefix/share/man/man3/MPI_Dims_create.3
rm -rf $prefix/share/man/man3/MPI_Dist_graph_create.3
rm -rf $prefix/share/man/man3/MPI_Dist_graph_create_adjacent.3
rm -rf $prefix/share/man/man3/MPI_Dist_graph_neighbors.3
rm -rf $prefix/share/man/man3/MPI_Dist_graph_neighbors_count.3
rm -rf $prefix/share/man/man3/MPI_Errhandler_create.3
rm -rf $prefix/share/man/man3/MPI_Errhandler_free.3
rm -rf $prefix/share/man/man3/MPI_Errhandler_get.3
rm -rf $prefix/share/man/man3/MPI_Errhandler_set.3
rm -rf $prefix/share/man/man3/MPI_Error_class.3
rm -rf $prefix/share/man/man3/MPI_Error_string.3
rm -rf $prefix/share/man/man3/MPI_Exscan.3
rm -rf $prefix/share/man/man3/MPI_Fetch_and_op.3
rm -rf $prefix/share/man/man3/MPI_File_c2f.3
rm -rf $prefix/share/man/man3/MPI_File_call_errhandler.3
rm -rf $prefix/share/man/man3/MPI_File_close.3
rm -rf $prefix/share/man/man3/MPI_File_create_errhandler.3
rm -rf $prefix/share/man/man3/MPI_File_delete.3
rm -rf $prefix/share/man/man3/MPI_File_f2c.3
rm -rf $prefix/share/man/man3/MPI_File_get_amode.3
rm -rf $prefix/share/man/man3/MPI_File_get_atomicity.3
rm -rf $prefix/share/man/man3/MPI_File_get_byte_offset.3
rm -rf $prefix/share/man/man3/MPI_File_get_errhandler.3
rm -rf $prefix/share/man/man3/MPI_File_get_group.3
rm -rf $prefix/share/man/man3/MPI_File_get_info.3
rm -rf $prefix/share/man/man3/MPI_File_get_position.3
rm -rf $prefix/share/man/man3/MPI_File_get_position_shared.3
rm -rf $prefix/share/man/man3/MPI_File_get_size.3
rm -rf $prefix/share/man/man3/MPI_File_get_type_extent.3
rm -rf $prefix/share/man/man3/MPI_File_get_view.3
rm -rf $prefix/share/man/man3/MPI_File_iread.3
rm -rf $prefix/share/man/man3/MPI_File_iread_at.3
rm -rf $prefix/share/man/man3/MPI_File_iread_shared.3
rm -rf $prefix/share/man/man3/MPI_File_iwrite.3
rm -rf $prefix/share/man/man3/MPI_File_iwrite_at.3
rm -rf $prefix/share/man/man3/MPI_File_iwrite_shared.3
rm -rf $prefix/share/man/man3/MPI_File_open.3
rm -rf $prefix/share/man/man3/MPI_File_preallocate.3
rm -rf $prefix/share/man/man3/MPI_File_read.3
rm -rf $prefix/share/man/man3/MPI_File_read_all.3
rm -rf $prefix/share/man/man3/MPI_File_read_all_begin.3
rm -rf $prefix/share/man/man3/MPI_File_read_all_end.3
rm -rf $prefix/share/man/man3/MPI_File_read_at.3
rm -rf $prefix/share/man/man3/MPI_File_read_at_all.3
rm -rf $prefix/share/man/man3/MPI_File_read_at_all_begin.3
rm -rf $prefix/share/man/man3/MPI_File_read_at_all_end.3
rm -rf $prefix/share/man/man3/MPI_File_read_ordered.3
rm -rf $prefix/share/man/man3/MPI_File_read_ordered_begin.3
rm -rf $prefix/share/man/man3/MPI_File_read_ordered_end.3
rm -rf $prefix/share/man/man3/MPI_File_read_shared.3
rm -rf $prefix/share/man/man3/MPI_File_seek.3
rm -rf $prefix/share/man/man3/MPI_File_seek_shared.3
rm -rf $prefix/share/man/man3/MPI_File_set_atomicity.3
rm -rf $prefix/share/man/man3/MPI_File_set_errhandler.3
rm -rf $prefix/share/man/man3/MPI_File_set_info.3
rm -rf $prefix/share/man/man3/MPI_File_set_size.3
rm -rf $prefix/share/man/man3/MPI_File_set_view.3
rm -rf $prefix/share/man/man3/MPI_File_sync.3
rm -rf $prefix/share/man/man3/MPI_File_write.3
rm -rf $prefix/share/man/man3/MPI_File_write_all.3
rm -rf $prefix/share/man/man3/MPI_File_write_all_begin.3
rm -rf $prefix/share/man/man3/MPI_File_write_all_end.3
rm -rf $prefix/share/man/man3/MPI_File_write_at.3
rm -rf $prefix/share/man/man3/MPI_File_write_at_all.3
rm -rf $prefix/share/man/man3/MPI_File_write_at_all_begin.3
rm -rf $prefix/share/man/man3/MPI_File_write_at_all_end.3
rm -rf $prefix/share/man/man3/MPI_File_write_ordered.3
rm -rf $prefix/share/man/man3/MPI_File_write_ordered_begin.3
rm -rf $prefix/share/man/man3/MPI_File_write_ordered_end.3
rm -rf $prefix/share/man/man3/MPI_File_write_shared.3
rm -rf $prefix/share/man/man3/MPI_Finalize.3
rm -rf $prefix/share/man/man3/MPI_Finalized.3
rm -rf $prefix/share/man/man3/MPI_Free_mem.3
rm -rf $prefix/share/man/man3/MPI_Gather.3
rm -rf $prefix/share/man/man3/MPI_Gatherv.3
rm -rf $prefix/share/man/man3/MPI_Get.3
rm -rf $prefix/share/man/man3/MPI_Get_accumulate.3
rm -rf $prefix/share/man/man3/MPI_Get_address.3
rm -rf $prefix/share/man/man3/MPI_Get_count.3
rm -rf $prefix/share/man/man3/MPI_Get_elements.3
rm -rf $prefix/share/man/man3/MPI_Get_elements_x.3
rm -rf $prefix/share/man/man3/MPI_Get_library_version.3
rm -rf $prefix/share/man/man3/MPI_Get_processor_name.3
rm -rf $prefix/share/man/man3/MPI_Get_version.3
rm -rf $prefix/share/man/man3/MPI_Graph_create.3
rm -rf $prefix/share/man/man3/MPI_Graph_get.3
rm -rf $prefix/share/man/man3/MPI_Graph_map.3
rm -rf $prefix/share/man/man3/MPI_Graph_neighbors.3
rm -rf $prefix/share/man/man3/MPI_Graph_neighbors_count.3
rm -rf $prefix/share/man/man3/MPI_Graphdims_get.3
rm -rf $prefix/share/man/man3/MPI_Grequest_complete.3
rm -rf $prefix/share/man/man3/MPI_Grequest_start.3
rm -rf $prefix/share/man/man3/MPI_Group_c2f.3
rm -rf $prefix/share/man/man3/MPI_Group_compare.3
rm -rf $prefix/share/man/man3/MPI_Group_difference.3
rm -rf $prefix/share/man/man3/MPI_Group_excl.3
rm -rf $prefix/share/man/man3/MPI_Group_f2c.3
rm -rf $prefix/share/man/man3/MPI_Group_free.3
rm -rf $prefix/share/man/man3/MPI_Group_incl.3
rm -rf $prefix/share/man/man3/MPI_Group_intersection.3
rm -rf $prefix/share/man/man3/MPI_Group_range_excl.3
rm -rf $prefix/share/man/man3/MPI_Group_range_incl.3
rm -rf $prefix/share/man/man3/MPI_Group_rank.3
rm -rf $prefix/share/man/man3/MPI_Group_size.3
rm -rf $prefix/share/man/man3/MPI_Group_translate_ranks.3
rm -rf $prefix/share/man/man3/MPI_Group_union.3
rm -rf $prefix/share/man/man3/MPI_Iallgather.3
rm -rf $prefix/share/man/man3/MPI_Iallgatherv.3
rm -rf $prefix/share/man/man3/MPI_Iallreduce.3
rm -rf $prefix/share/man/man3/MPI_Ialltoall.3
rm -rf $prefix/share/man/man3/MPI_Ialltoallv.3
rm -rf $prefix/share/man/man3/MPI_Ialltoallw.3
rm -rf $prefix/share/man/man3/MPI_Ibarrier.3
rm -rf $prefix/share/man/man3/MPI_Ibcast.3
rm -rf $prefix/share/man/man3/MPI_Ibsend.3
rm -rf $prefix/share/man/man3/MPI_Iexscan.3
rm -rf $prefix/share/man/man3/MPI_Igather.3
rm -rf $prefix/share/man/man3/MPI_Igatherv.3
rm -rf $prefix/share/man/man3/MPI_Improbe.3
rm -rf $prefix/share/man/man3/MPI_Imrecv.3
rm -rf $prefix/share/man/man3/MPI_Ineighbor_allgather.3
rm -rf $prefix/share/man/man3/MPI_Ineighbor_allgatherv.3
rm -rf $prefix/share/man/man3/MPI_Ineighbor_alltoall.3
rm -rf $prefix/share/man/man3/MPI_Ineighbor_alltoallv.3
rm -rf $prefix/share/man/man3/MPI_Ineighbor_alltoallw.3
rm -rf $prefix/share/man/man3/MPI_Info_c2f.3
rm -rf $prefix/share/man/man3/MPI_Info_create.3
rm -rf $prefix/share/man/man3/MPI_Info_delete.3
rm -rf $prefix/share/man/man3/MPI_Info_dup.3
rm -rf $prefix/share/man/man3/MPI_Info_env.3
rm -rf $prefix/share/man/man3/MPI_Info_f2c.3
rm -rf $prefix/share/man/man3/MPI_Info_free.3
rm -rf $prefix/share/man/man3/MPI_Info_get.3
rm -rf $prefix/share/man/man3/MPI_Info_get_nkeys.3
rm -rf $prefix/share/man/man3/MPI_Info_get_nthkey.3
rm -rf $prefix/share/man/man3/MPI_Info_get_valuelen.3
rm -rf $prefix/share/man/man3/MPI_Info_set.3
rm -rf $prefix/share/man/man3/MPI_Init.3
rm -rf $prefix/share/man/man3/MPI_Init_thread.3
rm -rf $prefix/share/man/man3/MPI_Initialized.3
rm -rf $prefix/share/man/man3/MPI_Intercomm_create.3
rm -rf $prefix/share/man/man3/MPI_Intercomm_merge.3
rm -rf $prefix/share/man/man3/MPI_Iprobe.3
rm -rf $prefix/share/man/man3/MPI_Irecv.3
rm -rf $prefix/share/man/man3/MPI_Ireduce.3
rm -rf $prefix/share/man/man3/MPI_Ireduce_scatter.3
rm -rf $prefix/share/man/man3/MPI_Ireduce_scatter_block.3
rm -rf $prefix/share/man/man3/MPI_Irsend.3
rm -rf $prefix/share/man/man3/MPI_Is_thread_main.3
rm -rf $prefix/share/man/man3/MPI_Iscan.3
rm -rf $prefix/share/man/man3/MPI_Iscatter.3
rm -rf $prefix/share/man/man3/MPI_Iscatterv.3
rm -rf $prefix/share/man/man3/MPI_Isend.3
rm -rf $prefix/share/man/man3/MPI_Issend.3
rm -rf $prefix/share/man/man3/MPI_Keyval_create.3
rm -rf $prefix/share/man/man3/MPI_Keyval_free.3
rm -rf $prefix/share/man/man3/MPI_Lookup_name.3
rm -rf $prefix/share/man/man3/MPI_Mprobe.3
rm -rf $prefix/share/man/man3/MPI_Mrecv.3
rm -rf $prefix/share/man/man3/MPI_Neighbor_allgather.3
rm -rf $prefix/share/man/man3/MPI_Neighbor_allgatherv.3
rm -rf $prefix/share/man/man3/MPI_Neighbor_alltoall.3
rm -rf $prefix/share/man/man3/MPI_Neighbor_alltoallv.3
rm -rf $prefix/share/man/man3/MPI_Neighbor_alltoallw.3
rm -rf $prefix/share/man/man3/MPI_Op_c2f.3
rm -rf $prefix/share/man/man3/MPI_Op_create.3
rm -rf $prefix/share/man/man3/MPI_Op_f2c.3
rm -rf $prefix/share/man/man3/MPI_Op_free.3
rm -rf $prefix/share/man/man3/MPI_Open_port.3
rm -rf $prefix/share/man/man3/MPI_Pack.3
rm -rf $prefix/share/man/man3/MPI_Pack_external.3
rm -rf $prefix/share/man/man3/MPI_Pack_external_size.3
rm -rf $prefix/share/man/man3/MPI_Pack_size.3
rm -rf $prefix/share/man/man3/MPI_Pcontrol.3
rm -rf $prefix/share/man/man3/MPI_Probe.3
rm -rf $prefix/share/man/man3/MPI_Publish_name.3
rm -rf $prefix/share/man/man3/MPI_Put.3
rm -rf $prefix/share/man/man3/MPI_Query_thread.3
rm -rf $prefix/share/man/man3/MPI_Raccumulate.3
rm -rf $prefix/share/man/man3/MPI_Recv.3
rm -rf $prefix/share/man/man3/MPI_Recv_init.3
rm -rf $prefix/share/man/man3/MPI_Reduce.3
rm -rf $prefix/share/man/man3/MPI_Reduce_local.3
rm -rf $prefix/share/man/man3/MPI_Reduce_scatter.3
rm -rf $prefix/share/man/man3/MPI_Reduce_scatter_block.3
rm -rf $prefix/share/man/man3/MPI_Register_datarep.3
rm -rf $prefix/share/man/man3/MPI_Request_c2f.3
rm -rf $prefix/share/man/man3/MPI_Request_f2c.3
rm -rf $prefix/share/man/man3/MPI_Request_free.3
rm -rf $prefix/share/man/man3/MPI_Request_get_status.3
rm -rf $prefix/share/man/man3/MPI_Rget.3
rm -rf $prefix/share/man/man3/MPI_Rget_accumulate.3
rm -rf $prefix/share/man/man3/MPI_Rput.3
rm -rf $prefix/share/man/man3/MPI_Rsend.3
rm -rf $prefix/share/man/man3/MPI_Rsend_init.3
rm -rf $prefix/share/man/man3/MPI_Scan.3
rm -rf $prefix/share/man/man3/MPI_Scatter.3
rm -rf $prefix/share/man/man3/MPI_Scatterv.3
rm -rf $prefix/share/man/man3/MPI_Send.3
rm -rf $prefix/share/man/man3/MPI_Send_init.3
rm -rf $prefix/share/man/man3/MPI_Sendrecv.3
rm -rf $prefix/share/man/man3/MPI_Sendrecv_replace.3
rm -rf $prefix/share/man/man3/MPI_Sizeof.3
rm -rf $prefix/share/man/man3/MPI_Ssend.3
rm -rf $prefix/share/man/man3/MPI_Ssend_init.3
rm -rf $prefix/share/man/man3/MPI_Start.3
rm -rf $prefix/share/man/man3/MPI_Startall.3
rm -rf $prefix/share/man/man3/MPI_Status_c2f.3
rm -rf $prefix/share/man/man3/MPI_Status_f2c.3
rm -rf $prefix/share/man/man3/MPI_Status_set_cancelled.3
rm -rf $prefix/share/man/man3/MPI_Status_set_elements.3
rm -rf $prefix/share/man/man3/MPI_Status_set_elements_x.3
rm -rf $prefix/share/man/man3/MPI_Test.3
rm -rf $prefix/share/man/man3/MPI_Test_cancelled.3
rm -rf $prefix/share/man/man3/MPI_Testall.3
rm -rf $prefix/share/man/man3/MPI_Testany.3
rm -rf $prefix/share/man/man3/MPI_Testsome.3
rm -rf $prefix/share/man/man3/MPI_Topo_test.3
rm -rf $prefix/share/man/man3/MPI_Type_c2f.3
rm -rf $prefix/share/man/man3/MPI_Type_commit.3
rm -rf $prefix/share/man/man3/MPI_Type_contiguous.3
rm -rf $prefix/share/man/man3/MPI_Type_create_darray.3
rm -rf $prefix/share/man/man3/MPI_Type_create_f90_complex.3
rm -rf $prefix/share/man/man3/MPI_Type_create_f90_integer.3
rm -rf $prefix/share/man/man3/MPI_Type_create_f90_real.3
rm -rf $prefix/share/man/man3/MPI_Type_create_hindexed.3
rm -rf $prefix/share/man/man3/MPI_Type_create_hindexed_block.3
rm -rf $prefix/share/man/man3/MPI_Type_create_hvector.3
rm -rf $prefix/share/man/man3/MPI_Type_create_indexed_block.3
rm -rf $prefix/share/man/man3/MPI_Type_create_keyval.3
rm -rf $prefix/share/man/man3/MPI_Type_create_resized.3
rm -rf $prefix/share/man/man3/MPI_Type_create_struct.3
rm -rf $prefix/share/man/man3/MPI_Type_create_subarray.3
rm -rf $prefix/share/man/man3/MPI_Type_delete_attr.3
rm -rf $prefix/share/man/man3/MPI_Type_dup.3
rm -rf $prefix/share/man/man3/MPI_Type_extent.3
rm -rf $prefix/share/man/man3/MPI_Type_f2c.3
rm -rf $prefix/share/man/man3/MPI_Type_free.3
rm -rf $prefix/share/man/man3/MPI_Type_free_keyval.3
rm -rf $prefix/share/man/man3/MPI_Type_get_attr.3
rm -rf $prefix/share/man/man3/MPI_Type_get_contents.3
rm -rf $prefix/share/man/man3/MPI_Type_get_envelope.3
rm -rf $prefix/share/man/man3/MPI_Type_get_extent.3
rm -rf $prefix/share/man/man3/MPI_Type_get_extent_x.3
rm -rf $prefix/share/man/man3/MPI_Type_get_name.3
rm -rf $prefix/share/man/man3/MPI_Type_get_true_extent.3
rm -rf $prefix/share/man/man3/MPI_Type_get_true_extent_x.3
rm -rf $prefix/share/man/man3/MPI_Type_hindexed.3
rm -rf $prefix/share/man/man3/MPI_Type_hvector.3
rm -rf $prefix/share/man/man3/MPI_Type_indexed.3
rm -rf $prefix/share/man/man3/MPI_Type_lb.3
rm -rf $prefix/share/man/man3/MPI_Type_match_size.3
rm -rf $prefix/share/man/man3/MPI_Type_set_attr.3
rm -rf $prefix/share/man/man3/MPI_Type_set_name.3
rm -rf $prefix/share/man/man3/MPI_Type_size.3
rm -rf $prefix/share/man/man3/MPI_Type_size_x.3
rm -rf $prefix/share/man/man3/MPI_Type_struct.3
rm -rf $prefix/share/man/man3/MPI_Type_ub.3
rm -rf $prefix/share/man/man3/MPI_Type_vector.3
rm -rf $prefix/share/man/man3/MPI_Unpack.3
rm -rf $prefix/share/man/man3/MPI_Unpack_external.3
rm -rf $prefix/share/man/man3/MPI_Unpublish_name.3
rm -rf $prefix/share/man/man3/MPI_Wait.3
rm -rf $prefix/share/man/man3/MPI_Waitall.3
rm -rf $prefix/share/man/man3/MPI_Waitany.3
rm -rf $prefix/share/man/man3/MPI_Waitsome.3
rm -rf $prefix/share/man/man3/MPI_Win_c2f.3
rm -rf $prefix/share/man/man3/MPI_Win_call_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Win_complete.3
rm -rf $prefix/share/man/man3/MPI_Win_create.3
rm -rf $prefix/share/man/man3/MPI_Win_create_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Win_create_keyval.3
rm -rf $prefix/share/man/man3/MPI_Win_delete_attr.3
rm -rf $prefix/share/man/man3/MPI_Win_f2c.3
rm -rf $prefix/share/man/man3/MPI_Win_fence.3
rm -rf $prefix/share/man/man3/MPI_Win_flush.3
rm -rf $prefix/share/man/man3/MPI_Win_flush_all.3
rm -rf $prefix/share/man/man3/MPI_Win_flush_local.3
rm -rf $prefix/share/man/man3/MPI_Win_flush_local_all.3
rm -rf $prefix/share/man/man3/MPI_Win_free.3
rm -rf $prefix/share/man/man3/MPI_Win_free_keyval.3
rm -rf $prefix/share/man/man3/MPI_Win_get_attr.3
rm -rf $prefix/share/man/man3/MPI_Win_get_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Win_get_group.3
rm -rf $prefix/share/man/man3/MPI_Win_get_name.3
rm -rf $prefix/share/man/man3/MPI_Win_lock.3
rm -rf $prefix/share/man/man3/MPI_Win_lock_all.3
rm -rf $prefix/share/man/man3/MPI_Win_post.3
rm -rf $prefix/share/man/man3/MPI_Win_set_attr.3
rm -rf $prefix/share/man/man3/MPI_Win_set_errhandler.3
rm -rf $prefix/share/man/man3/MPI_Win_set_name.3
rm -rf $prefix/share/man/man3/MPI_Win_start.3
rm -rf $prefix/share/man/man3/MPI_Win_sync.3
rm -rf $prefix/share/man/man3/MPI_Win_test.3
rm -rf $prefix/share/man/man3/MPI_Win_unlock.3
rm -rf $prefix/share/man/man3/MPI_Win_unlock_all.3
rm -rf $prefix/share/man/man3/MPI_Win_wait.3
rm -rf $prefix/share/man/man3/MPI_Wtick.3
rm -rf $prefix/share/man/man3/MPI_Wtime.3
rm -rf $prefix/share/man/man3/OpenMPI.3
rm -rf $prefix/share/man/man7/ompi_crcp.7
rm -rf $prefix/share/man/man7/opal_crs.7
rm -rf $prefix/share/man/man7/orte_filem.7
rm -rf $prefix/share/man/man7/orte_hosts.7
rm -rf $prefix/share/man/man7/orte_snapc.7
rm -rf $prefix/share/man/man7/orte_sstore.7
rm -rf $prefix/share/openmpi
rm -rf $prefix/share/vampirtrace
